"""
Milestone 5c: event-study backtest orchestrator (SPEC Ch.19/20, SPEC_ADDENDUM A-2/A-3/
B-2/B-3). Reads the 60 days of already-persisted M5c-prep artifacts on disk (signal
events, per-day scored sector/stock frames, FinMind per-stock OHLCV, TAIEX index) and
produces:

  - `outputs/backtests/backtest_report_<date>.xlsx`: signal-tier headline stats,
    UNTRADABLE accounting (exclude vs postpone), vs-benchmark comparison, event detail.
  - `docs/backtest_methodology.md` (static, hand-written -- not generated by this
    script; describes the event definition, forward-return convention, cost model).

Usage:
  python scripts/run_backtest.py
  python scripts/run_backtest.py --n-bootstrap 10000   # full SPEC_ADDENDUM 3.2 N

This script is read-only with respect to every already-accepted M0-M5c-prep artifact --
it never writes into data/raw or data/processed, only outputs/backtests and docs/.
"""

import os
import sys
import glob
import json
import argparse
import datetime
from typing import Dict, List, Optional

import numpy as np
import pandas as pd
from loguru import logger

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../")))

from src.backtester import Backtester, HORIZONS_DAYS, extract_events
from src.benchmarks import (
    momentum_extension_baseline,
    random_sector_bootstrap_baseline,
    bootstrap_confidence_interval,
)
from src.price_adjuster import apply_adjustment
from src.disposition_fetcher import DISPOSITION_ENDPOINTS, DispositionFetcher
from src.config_manager import ConfigManager


def _default_data_dir() -> str:
    return "C:/Workspace_CN/taiwan_moneyflow_rotation/data"


def _default_output_dir() -> str:
    return "C:/Workspace_CN/taiwan_moneyflow_rotation/outputs"


def load_all_signals(data_dir_signals: str) -> pd.DataFrame:
    """Reads every outputs/signals/signals_<date>.jsonl into one stacked frame."""
    frames = []
    for path in sorted(glob.glob(os.path.join(data_dir_signals, "signals_*.jsonl"))):
        rows = []
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                rows.append(json.loads(line))
        if rows:
            frames.append(pd.DataFrame(rows))
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)


def load_scored_by_date(data_dir_processed: str, prefix: str) -> Dict[str, pd.DataFrame]:
    """Reads data/processed/<prefix>_<date>.csv for every date on disk (excludes any
    _bak_* backup subdirectories/files, which are pre-rerun snapshots, not live data)."""
    out: Dict[str, pd.DataFrame] = {}
    pattern = os.path.join(data_dir_processed, f"{prefix}_*.csv")
    for path in sorted(glob.glob(pattern)):
        fname = os.path.basename(path)
        if "_bak_" in fname:
            continue
        date_str = fname.replace(f"{prefix}_", "").replace(".csv", "")
        try:
            out[date_str] = pd.read_csv(path, dtype={"stock_id": str})
        except Exception as e:
            logger.warning(f"load_scored_by_date: failed to read {path}: {e}")
    return out


def load_finmind_ohlcv_history(data_dir_ohlcv: str) -> pd.DataFrame:
    """Reads every data/raw/ohlcv/finmind_<stock_id>.json into one stacked
    (stock_id, trade_date, open/high/low/close/volume) frame."""
    rows = []
    for path in sorted(glob.glob(os.path.join(data_dir_ohlcv, "finmind_*.json"))):
        fname = os.path.basename(path)
        if fname == "_smoke_twse_sample.json" or not fname.startswith("finmind_"):
            continue
        stock_id = fname.replace("finmind_", "").replace(".json", "")
        try:
            with open(path, "r", encoding="utf-8") as f:
                env = json.load(f)
        except Exception as e:
            logger.warning(f"load_finmind_ohlcv_history: unreadable {path}: {e}")
            continue
        for r in env.get("payload", []) or []:
            try:
                rows.append({
                    "stock_id": stock_id, "trade_date": r["date"],
                    "open": float(r["open"]), "high": float(r["max"]), "low": float(r["min"]),
                    "close": float(r["close"]), "volume": float(r.get("Trading_Volume") or 0.0),
                })
            except (KeyError, TypeError, ValueError):
                continue
    return pd.DataFrame(rows)


def load_adjustment_factors(data_dir: str) -> pd.DataFrame:
    """M7: reads data/reference/price_adjustment_factors.csv (built by
    scripts/fetch_price_adjustments.py). Empty DataFrame (not an error) if the file
    doesn't exist yet -- callers must treat every stock as UNADJUSTED in that case."""
    path = os.path.join(data_dir, "reference", "price_adjustment_factors.csv")
    if not os.path.exists(path):
        logger.warning(f"load_adjustment_factors: {path} not found -- all prices will be "
                        f"treated as UNADJUSTED (run scripts/fetch_price_adjustments.py first).")
        return pd.DataFrame(columns=["stock_id", "trade_date", "adj_factor"])
    return pd.read_csv(path, dtype={"stock_id": str})


def apply_price_adjustment(df_ohlcv: pd.DataFrame, data_dir: str, use_adjusted_prices: bool) -> tuple:
    """
    M7: if `use_adjusted_prices`, merges in adjustment factors and OVERWRITES
    open/high/low/close with the adjusted values wherever a factor is known (a new
    `price_unadjusted` bool column marks the rest, per-row, so status can be reported
    accurately even when adjustment is enabled but coverage is partial). If
    `use_adjusted_prices` is False, prices pass through unchanged and every row is
    marked `price_unadjusted=True` (honest: nothing was adjusted, not merely "wasn't
    tried"). Returns (df_ohlcv_possibly_adjusted, unadjusted_stock_pct).
    """
    if df_ohlcv.empty:
        return df_ohlcv, None
    if not use_adjusted_prices:
        out = df_ohlcv.copy()
        out["price_unadjusted"] = True
        return out, 1.0

    df_factors = load_adjustment_factors(data_dir)
    merged = apply_adjustment(df_ohlcv, df_factors)
    for raw_col, adj_col in (("open", "adj_open"), ("high", "adj_high"),
                              ("low", "adj_low"), ("close", "adj_close")):
        # Only overwrite where a real factor was found; price_unadjusted rows keep
        # their original raw value (apply_adjustment already does this per-row).
        merged[raw_col] = merged[adj_col]
    merged = merged.drop(columns=["adj_open", "adj_high", "adj_low", "adj_close"], errors="ignore")

    n_stocks_total = merged["stock_id"].nunique()
    n_stocks_unadjusted = merged.loc[merged["price_unadjusted"], "stock_id"].nunique()
    unadjusted_pct = round(n_stocks_unadjusted / n_stocks_total, 4) if n_stocks_total else None
    logger.info(f"apply_price_adjustment: {n_stocks_total - n_stocks_unadjusted}/{n_stocks_total} "
                f"stocks have real adjustment coverage; {n_stocks_unadjusted} UNADJUSTED "
                f"({unadjusted_pct:.1%} of universe) -- see backtest_summary JSON's "
                f"'unadjusted_stock_pct' field.")
    return merged, unadjusted_pct


def load_disposition_stock_ids(data_dir: str) -> dict:
    """
    M7: union of every stock_id that appeared on ANY disposition/attention raw-endpoint
    file on disk (across all dates -- this project only has TODAY's live snapshot, not
    a historical archive per date, since these endpoints themselves are "current status"
    APIs with no date-range query parameter; see src/disposition_fetcher.py module
    docstring). Returns {"disposition_stock_ids": set, "dates_covered": [...]} so the
    caller can honestly disclose this is a same-day-only signal, not a true historical
    per-event disposition history for the 60-day backtest window.
    """
    disp_dir = os.path.join(data_dir, "raw", "disposition")
    ids = set()
    dates_covered = set()
    if not os.path.isdir(disp_dir):
        return {"disposition_stock_ids": ids, "dates_covered": []}
    for path in sorted(glob.glob(os.path.join(disp_dir, "*.json"))):
        fname = os.path.basename(path)
        matched_key = None
        for key in DISPOSITION_ENDPOINTS:
            if fname.startswith(key + "_"):
                matched_key = key
                break
        if matched_key is None:
            continue
        date_str = fname.replace(matched_key + "_", "").replace(".json", "")
        dates_covered.add(date_str)
        try:
            with open(path, "r", encoding="utf-8") as f:
                envelope = json.load(f)
        except Exception as e:
            logger.warning(f"load_disposition_stock_ids: unreadable {path}: {e}")
            continue
        spec = DISPOSITION_ENDPOINTS[matched_key]
        for row in envelope.get("payload", []) or []:
            sid = DispositionFetcher._extract_stock_id(row, spec)
            if sid:
                ids.add(sid)
    return {"disposition_stock_ids": ids, "dates_covered": sorted(dates_covered)}


def load_taiex(data_dir_market_index: str) -> pd.DataFrame:
    path = os.path.join(data_dir_market_index, "finmind_index_twse.json")
    if not os.path.exists(path):
        logger.error(f"load_taiex: {path} not found -- market benchmark will be UNAVAILABLE.")
        return pd.DataFrame()
    with open(path, "r", encoding="utf-8") as f:
        env = json.load(f)
    rows = [{"trade_date": r["date"], "close": float(r["close"])} for r in env.get("payload", [])
            if r.get("close") is not None]
    return pd.DataFrame(rows)


def summarize_tier(df_events: pd.DataFrame, signal_type: str, horizon: int = None,
                    excess_col_prefix: str = "excess_return_net") -> dict:
    """Headline stats for one signal grade: independent event count, cost-adjusted
    excess-return median/mean, win rate. n<30 is explicitly flagged per SPEC_ADDENDUM
    B-3.3/M5c brief's "樣本不足不可裁決" instruction rather than silently reported as if
    decisive."""
    sub = df_events[df_events["signal_type"] == signal_type]
    horizon = horizon or 10
    col = f"{excess_col_prefix}_{horizon}d"
    if col not in sub.columns:
        return {"signal_type": signal_type, "n_events": len(sub), "n_realized": 0,
                "median_excess_pct": None, "mean_excess_pct": None, "win_rate": None,
                "sample_sufficient": False}
    realized = sub[col].dropna()
    n = len(realized)
    return {
        "signal_type": signal_type,
        "n_events": len(sub),
        "n_realized": n,
        "median_excess_pct": float(realized.median() * 100) if n > 0 else None,
        "mean_excess_pct": float(realized.mean() * 100) if n > 0 else None,
        "win_rate": float((realized > 0).mean()) if n > 0 else None,
        "sample_sufficient": n >= 30,
    }


def compare_vs_momentum_baseline(df_events: pd.DataFrame, df_momentum: pd.DataFrame,
                                  horizon: int = 10) -> dict:
    """SPEC_ADDENDUM A-3.3: signal excess return vs momentum-baseline excess return at
    the same horizon. Returns medians of each distribution and whether the signal median
    beats the baseline median -- a simple, disclosed comparison, NOT a formal
    significance test (no t-test/Mann-Whitney is run; SPEC_ADDENDUM only requires the
    comparison exist and be honestly reported, and this milestone's small n at most
    grades makes a formal test result likely underpowered/misleading if presented
    without heavy caveats better handled in report prose than a boolean)."""
    col = f"excess_return_net_{horizon}d"
    sig_vals = df_events[col].dropna() if col in df_events.columns else pd.Series(dtype=float)
    base_col = f"excess_return_{horizon}d"
    base_vals = df_momentum[base_col].dropna() if base_col in df_momentum.columns else pd.Series(dtype=float)
    sig_median = float(sig_vals.median() * 100) if len(sig_vals) > 0 else None
    base_median = float(base_vals.median() * 100) if len(base_vals) > 0 else None
    beats_baseline = (sig_median is not None and base_median is not None and sig_median > base_median)
    return {
        "horizon_days": horizon,
        "signal_n": len(sig_vals), "signal_median_excess_pct": sig_median,
        "baseline_n": len(base_vals), "baseline_median_excess_pct": base_median,
        "signal_beats_baseline": beats_baseline,
    }


def build_report_workbook(output_path: str, headline: dict, df_events: pd.DataFrame,
                           df_momentum: pd.DataFrame, df_random: pd.DataFrame,
                           untradable_stats: dict, disclosures: List[str]) -> None:
    import openpyxl
    from openpyxl.styles import Font, Alignment, PatternFill

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Headline"

    bold = Font(bold=True)
    warn_fill = PatternFill(start_color="FFF3CD", end_color="FFF3CD", fill_type="solid")

    ws["A1"] = "Milestone 5c Backtest -- Headline (初步研究讀數, 非 Research Ready)"
    ws["A1"].font = Font(bold=True, size=14)
    ws["A2"] = "門檻未經台股實證校準；結論等級最高只能標「初步研究讀數」(SPEC_ADDENDUM B-1)"
    ws["A2"].fill = warn_fill

    row = 4
    ws.cell(row=row, column=1, value="Signal Tier").font = bold
    for i, h in enumerate(["n_events", "n_realized (10d)", "median_excess_%_net", "mean_excess_%_net",
                            "win_rate", "sample_sufficient(n>=30)"]):
        ws.cell(row=row, column=2 + i, value=h).font = bold
    row += 1
    for tier_name, stats in headline.get("tiers", {}).items():
        ws.cell(row=row, column=1, value=tier_name)
        ws.cell(row=row, column=2, value=stats["n_events"])
        ws.cell(row=row, column=3, value=stats["n_realized"])
        ws.cell(row=row, column=4, value=stats["median_excess_pct"])
        ws.cell(row=row, column=5, value=stats["mean_excess_pct"])
        ws.cell(row=row, column=6, value=stats["win_rate"])
        ws.cell(row=row, column=7, value=stats["sample_sufficient"])
        row += 1

    row += 2
    ws.cell(row=row, column=1, value="vs Momentum Baseline (10d)").font = bold
    row += 1
    for tier_name, comp in headline.get("vs_momentum", {}).items():
        ws.cell(row=row, column=1, value=tier_name)
        ws.cell(row=row, column=2, value=f"signal_median={comp['signal_median_excess_pct']}")
        ws.cell(row=row, column=3, value=f"baseline_median={comp['baseline_median_excess_pct']}")
        ws.cell(row=row, column=4, value=f"beats_baseline={comp['signal_beats_baseline']}")
        row += 1

    row += 2
    ws.cell(row=row, column=1, value="UNTRADABLE (limit-up lockout) accounting").font = bold
    row += 1
    for k, v in untradable_stats.items():
        ws.cell(row=row, column=1, value=k)
        ws.cell(row=row, column=2, value=str(v))
        row += 1

    row += 2
    ws.cell(row=row, column=1, value="Known Limitations / Disclosures").font = bold
    row += 1
    for d in disclosures:
        ws.cell(row=row, column=1, value=d)
        row += 1

    for col_letter in "ABCDEFG":
        ws.column_dimensions[col_letter].width = 34

    ws_events = wb.create_sheet("Event Detail")
    _write_df(ws_events, df_events)

    ws_mom = wb.create_sheet("Momentum Baseline")
    _write_df(ws_mom, df_momentum)

    ws_rand = wb.create_sheet("Random Baseline (sample)")
    _write_df(ws_rand, df_random.head(500))  # cap sheet size; full sample summarized on Headline

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    wb.save(output_path)
    logger.info(f"Backtest report written to {output_path}")


def _write_df(ws, df: pd.DataFrame) -> None:
    from openpyxl.utils.dataframe import dataframe_to_rows
    if df is None or df.empty:
        ws["A1"] = "(no rows)"
        return
    for r in dataframe_to_rows(df, index=False, header=True):
        ws.append(r)


def run(data_dir: Optional[str] = None, output_dir: Optional[str] = None,
        n_bootstrap: int = 10000, report_date: Optional[str] = None,
        use_adjusted_prices: Optional[bool] = None) -> dict:
    data_dir = data_dir or _default_data_dir()
    output_dir = output_dir or _default_output_dir()
    report_date = report_date or datetime.date.today().isoformat()

    if use_adjusted_prices is None:
        use_adjusted_prices = bool(ConfigManager().get("backtest.use_adjusted_prices", True))

    logger.info("Loading signals, scored frames, OHLCV, TAIEX from disk...")
    df_signals = load_all_signals(os.path.join(output_dir, "signals"))
    df_sector_scored_by_date = load_scored_by_date(os.path.join(data_dir, "processed"), "sector_scored")
    df_stock_scored_by_date = load_scored_by_date(os.path.join(data_dir, "processed"), "stock_scored")
    df_ohlcv = load_finmind_ohlcv_history(os.path.join(data_dir, "raw", "ohlcv"))
    df_taiex = load_taiex(os.path.join(data_dir, "raw", "market_index"))

    n_stocks_finmind = df_ohlcv["stock_id"].nunique() if not df_ohlcv.empty else 0
    logger.info(f"Loaded {len(df_signals)} signal rows, {len(df_sector_scored_by_date)} sector-scored days, "
                f"{n_stocks_finmind} FinMind-covered stocks, {len(df_taiex)} TAIEX rows.")

    if df_signals.empty or df_ohlcv.empty or df_taiex.empty:
        logger.error("run_backtest: missing required inputs (signals/OHLCV/TAIEX). Aborting.")
        return {"status": "ABORTED_MISSING_INPUTS"}

    # M7: ex-dividend backward adjustment (config/default.yaml backtest.use_adjusted_prices,
    # default true). Stocks without a computed factor keep their raw price, tagged
    # UNADJUSTED (price_unadjusted=True) -- never silently mixed with adjusted prices
    # without a way to tell them apart downstream.
    df_ohlcv, unadjusted_stock_pct = apply_price_adjustment(df_ohlcv, data_dir, use_adjusted_prices)

    # M7: disposition/attention stock ids (same-day snapshot only -- see
    # load_disposition_stock_ids docstring for the honest scope limitation).
    disposition_info = load_disposition_stock_ids(data_dir)
    disposition_stock_ids = disposition_info["disposition_stock_ids"]
    logger.info(f"Loaded {len(disposition_stock_ids)} disposition/attention stock_ids "
                f"(same-day snapshot(s): {disposition_info['dates_covered']}).")

    bt = Backtester(fee_pct=0.001425, tax_pct=0.003, slippage_pct=0.001, limit_up_handling="exclude")
    df_events = bt.run_event_study(df_signals, df_stock_scored_by_date, df_ohlcv, df_taiex,
                                    horizons=HORIZONS_DAYS, disposition_stock_ids=disposition_stock_ids)
    logger.info(f"Event study produced {len(df_events)} independent events "
                f"(exclude accounting; see status_postpone columns for postpone accounting).")

    # UNTRADABLE accounting (both conventions, per SPEC_ADDENDUM B-2.1's "both metrics
    # must be reported for comparison")
    untradable_stats = {}
    if not df_events.empty:
        untradable_stats["total_events"] = len(df_events)
        untradable_stats["untradable_exclude"] = int((df_events["status"] == "UNTRADABLE").sum())
        untradable_stats["pending_exclude"] = int((df_events["status"] == "PENDING").sum())
        untradable_stats["tradable_exclude"] = int((df_events["status"] == "TRADABLE").sum())
        untradable_stats["untradable_postpone"] = int((df_events["status_postpone"] == "UNTRADABLE").sum())
        untradable_stats["tradable_postpone"] = int((df_events["status_postpone"] == "TRADABLE").sum())

    # Benchmarks (SPEC_ADDENDUM A-3)
    logger.info("Computing momentum-extension baseline...")
    df_momentum = momentum_extension_baseline(df_sector_scored_by_date, df_stock_scored_by_date,
                                               df_ohlcv, df_taiex, horizons=HORIZONS_DAYS)
    logger.info(f"Momentum baseline: {len(df_momentum)} daily observations.")

    logger.info(f"Computing random sector bootstrap baseline (N={n_bootstrap})...")
    df_random = random_sector_bootstrap_baseline(df_sector_scored_by_date, df_stock_scored_by_date,
                                                  df_ohlcv, df_taiex, n_draws=n_bootstrap,
                                                  horizons=HORIZONS_DAYS, random_seed=42)
    logger.info(f"Random baseline: {len(df_random)} resolved draws (requested {n_bootstrap}).")

    # Headline per-tier stats
    tiers = {}
    vs_momentum = {}
    for signal_type in sorted(df_events["signal_type"].dropna().unique()) if not df_events.empty else []:
        tiers[signal_type] = summarize_tier(df_events, signal_type, horizon=10)
        sub = df_events[df_events["signal_type"] == signal_type]
        vs_momentum[signal_type] = compare_vs_momentum_baseline(sub, df_momentum, horizon=10)

    n_param_combinations_tested = 1  # this milestone runs exactly one config (config/default.yaml
                                      # backtest.* + the single limit_up_handling="exclude" primary
                                      # convention, with postpone reported alongside for comparison,
                                      # not as a second tuned configuration) -- SPEC_ADDENDUM B-3.3
                                      # multiple-comparison disclosure.

    disclosures = [
        f"歷史 OHLCV {n_stocks_finmind}/1963 檔 -> 族群成分不完整，廣度/占比在歷史段是部分樣本",
        "法人/融資券歷史近乎缺失 (institutional/margin 覆蓋率低) -> 歷史訊號的法人因子=中性 50 回退",
        "門檻未校準 (config/default.yaml 全部標記 PLACEHOLDER - UNCALIBRATED)",
        "60 天全在同一市場環境，無環境分層 (SPEC §18 分層留待資料累積)",
        (f"M7: 除權息調整{'已啟用' if use_adjusted_prices else '未啟用 (use_adjusted_prices=false)'}"
         f"（來源: FinMind TaiwanStockDividendResult 自算調整因子，非官方調整價資料集——"
         f"官方 adjusted-price dataset 於本 token 不可用，見乾跑收據）；"
         f"UNADJUSTED（無調整因子可用，使用原始價）股票比例="
         f"{f'{unadjusted_stock_pct:.1%}' if unadjusted_stock_pct is not None else 'N/A'}"),
        (f"M7: 處置/注意股名單已接線，共 {len(disposition_stock_ids)} 檔 "
         f"(快照日期: {disposition_info['dates_covered']})——僅為「當前即時狀態」快照，"
         f"TWSE/TPEx 該類端點無歷史日期查詢參數，無法回溯 60 天視窗內每日的處置/注意狀態，"
         f"故本欄為同一組 id 套用到全部歷史事件，非逐日精確歸戶。"),
        "本輪測試參數組合數 = 1 (單一 config，postpone 為對照口徑而非第二組調參)",
        "結論等級：初步研究讀數 (PRELIMINARY RESEARCH READING)，非 Research Ready",
    ]

    headline = {"tiers": tiers, "vs_momentum": vs_momentum,
                "n_param_combinations_tested": n_param_combinations_tested,
                "use_adjusted_prices": use_adjusted_prices,
                "unadjusted_stock_pct": unadjusted_stock_pct,
                "disposition_stock_count": len(disposition_stock_ids)}

    report_path = os.path.join(output_dir, "backtests", f"backtest_report_{report_date}.xlsx")
    build_report_workbook(report_path, headline, df_events, df_momentum, df_random,
                           untradable_stats, disclosures)

    # Also dump the raw event/momentum/random frames as CSV for programmatic reuse /
    # verifier spot-checks (Excel round-tripping can lose float precision).
    csv_dir = os.path.join(output_dir, "backtests")
    df_events.to_csv(os.path.join(csv_dir, f"backtest_events_{report_date}.csv"), index=False, encoding="utf-8-sig")
    df_momentum.to_csv(os.path.join(csv_dir, f"backtest_momentum_baseline_{report_date}.csv"), index=False, encoding="utf-8-sig")
    df_random.to_csv(os.path.join(csv_dir, f"backtest_random_baseline_{report_date}.csv"), index=False, encoding="utf-8-sig")

    summary = {
        "status": "SUCCESS",
        "report_date": report_date,
        "n_events": len(df_events),
        "untradable_stats": untradable_stats,
        "tiers": tiers,
        "vs_momentum": vs_momentum,
        "report_path": report_path,
        "use_adjusted_prices": use_adjusted_prices,
        "unadjusted_stock_pct": unadjusted_stock_pct,
        "disposition_stock_count": len(disposition_stock_ids),
        "disposition_snapshot_dates": disposition_info["dates_covered"],
    }
    summary_path = os.path.join(csv_dir, f"backtest_summary_{report_date}.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2, default=str)
    logger.info(f"Backtest summary written to {summary_path}")
    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Milestone 5c/M7 event-study backtest.")
    parser.add_argument("--n-bootstrap", type=int, default=10000,
                         help="Random sector bootstrap draw count (SPEC_ADDENDUM 3.2 default 10000).")
    parser.add_argument("--report-date", type=str, default=None)
    parser.add_argument("--no-adjusted-prices", action="store_true",
                         help="M7: disable ex-dividend price adjustment (default: enabled, "
                              "per config/default.yaml backtest.use_adjusted_prices).")
    args = parser.parse_args()

    use_adj = None if not args.no_adjusted_prices else False
    result = run(n_bootstrap=args.n_bootstrap, report_date=args.report_date,
                 use_adjusted_prices=use_adj)
    print(json.dumps(result, ensure_ascii=False, indent=2, default=str))
